### PR TITLE
Update: Refactor the way repositories are injected to the UOW

### PR DESCRIPTION
**Pull request by Morzkat**

### CODE REVIEW

**Comment by Jadhielv** [comment]
Check this @nminaya

**Review by Jadhielv — CHANGES_REQUESTED** [review]
@Morzkat remove **appsettings.json**

**Comment by nminaya** [comment]
> Check this @nminaya

It's a good improvement

**Comment by Jadhielv** [comment]
> 
> 
> > Check this @nminaya
> 
> It's a good improvement

Thanks @nminaya . LGTM! Nice work @Morzkat

**Review by Jadhielv — APPROVED** [review]

**Pull request merged**
